library(fastmatch)

peptides = read.delim("BPBR.csv", sep = ",", stringsAsFactors = F) #the file was downloaded from https://adaptivepublic.blob.core.windows.net/publishedproject-supplements/covid-2020/ImmuneCODE-MIRA-Release002.zip. The file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1).
peptide_seqs = unlist(strsplit(peptides$index, ","))

load("tpr_score") #The file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1) or generated by the calculation_of_thymoproteasomal_and_immunoproteasomal_cleavage_scores.Rmd script
thymomedians = sapply(score_list, FUN = function(x) median(x, na.rm = T))
load("pentamerfreq_tcem") #the file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1) or generated by the data_construction.Rmd script
load("expr_list_tcem") #the file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1) or generated by the creation_of_expr_list_object.Rmd script
exprmedians = sapply(expr_list, FUN = function(x) median(x, na.rm = T))


exprcutoff = 0.203075 #33th percentile of peptide TCEM expression in the naive CD8+ T cell analysis of healthy individuals
thymocutoff = 0.914470 #25th percentile of peptide TCEM thymoproteasome score in the naive CD8+ T cell analysis of healthy individuals

tcems = substr(peptide_seqs, 4, 8)
tcemfreq = pentamerfreq_tcem[fmatch(tcems, names(pentamerfreq_tcem))]
tcemexpr = exprmedians[fmatch(tcems, names(exprmedians))]
tcemthymo = thymomedians[fmatch(tcems, names(thymomedians))]


write.csv(tcemfreq,"tcemfreq_BPBR.csv")
write.csv(tcemexpr,"tcemexpr_BPBR.csv")
write.csv(tcemthymo, "tcemthymo_BPBR.csv")

